exports.groceryCategories = [
    "Uncategorized",
    "Baking",
    "Beverages",
    "Bread/Bakery",
    "Canned Goods",
    "Cereal/Breakfast",
    "Condiments",
    "Dairy/Dairy Free",
    "Deli",
    "Frozen Foods",
    "Meats",
    "Non-Food Items",
    "Pasta/Rice",
    "Produce",
    "Snacks",
    "Sweets/Desserts",
    "Spices",
    "Other",
]